### ISSUE TITLE
The icon for KG disappears

### ISSUE THREAD

**Issue by qingfof** [yjcyxky/biomedgps#3]
In split screen mode on win or mac, the KG icon occasionally disappears.

**Comment by yjcyxky** [comment]
> In split screen mode on win or mac, the KG icon occasionally disappears.

Hi, thanks for your feedback. Could you give me more details? If possible, please fill some information according to the following template.

**Issue Type**:
- [ ] Bug Report
- [ ] Feature Request

**Project Version**:
[Please specify the project version or a commit number here]

**Issue Description**:
Provide a detailed description of the issue. please include reproduction steps, including input, output, and expected results.

**Reproduction Steps** (If possible):
1. Step 1
2. Step 2
3. Step 3

**Screenshots** (if applicable):
Add screenshots of the issue to help better understand it.

**Environment Information**:
- Operating System: [e.g., Windows 10]
- Browser and version (if applicable): [e.g., Chrome, Firefox, Safari]

**Additional Information**:
Add any other information or context to help us better understand the issue or request.

**Reproduction Link** (if available):
Provide any online demos or sample code to help reproduce the issue.

**Comment by qingfof** [comment]
Hello, I'd be happy to provide more details on the bug.

It appears that the reason for the KG icon disappearing is its conflict with some Chrome extensions, such as EasyPubMedicine. Both icons happen to be located in the bottom-right corner of the screen.

Operating System: Windows 11
Browser and version: Chrome

Reproduction Steps:
1. Open Label Studio (KG icon displays correctly at this point).
2. Run EasyPubMedicine (KG icon disappears).

Would it be possible to make the KG icon movable?

Thank you for your assistance.

![image](https://github.com/yjcyxky/biomedgps/assets/149316244/8977820d-09f3-44cf-b201-1c41ff63c93c)

**Comment by yjcyxky** [comment]
Looks like that the logo of another extension is on the top of ours'. You can disable that extension temporarily.
